### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by graingerkid** [crisbal/flask-blog-blueprint#1]
Hey, 

I'm trying to use your blueprint, I have followed the instructions but I am getting an error, specifically "OperationalError: no such table: post".

I've not actually used peewee before but is there something wrong or am I supposed to be creating the database?

**Comment by crisbal** [comment]
Hey,

Thank you for the report, I actually forgot to add this to the instructions, you also need to execute:

```
python setup.py
```

after setting up the blueprint which creates the required tables for the blog and adds a few example posts.

I haven't really worked on this project for a long time but you just gave me a reason to fix some things. 

I hope this will fix your problem, if you still have any question feel free to ask.

**Comment by crisbal** [comment]
Also when I was working on this project I was not the best at both HTML/CSS/JS and Python so don't expect the best looking and most interesting blog Blueprint: at least it is better than nothing and you can customize it a little bit. :+1:

**Comment by graingerkid** [comment]
Hey, thanks for coming back to me, I'm not seeing a setup.py?

EDIT: I see it :p

**Comment by crisbal** [comment]
It is in the main folder of the project, not in the "blog" folder.  

https://github.com/crisbal/flask-blog-blueprint/blob/master/setup.py

**Comment by graingerkid** [comment]
grrr, still getting the same error despite there now being a Blog.db file.

Nothing obvious I'm missing, if your routes are untouched the default location to log in would be /blog/admin/login/

**Comment by crisbal** [comment]
Try to restart the main app.

Does the same problem happens if you execute the same steps from a clean download?

**Comment by graingerkid** [comment]
I'll have a go now

**Comment by graingerkid** [comment]
Still OperationalError: no such table: post

I have looked at the .db file with sqliteman and the tables are there so I don't get it.

To confirm the .db file should be in the main application directory not in the blog directory? I have tried it in both without it working.

**Comment by crisbal** [comment]
Blog.db should be in the main directory.

Are you on Windows or on Linux/Mac? If you are on Linux/Mac how are the file permissions on Blog.db? 

Mine are like this:
![image](https://cloud.githubusercontent.com/assets/2728038/7661291/9bbe8402-fb51-11e4-8389-90eacf9e1588.png)

If you don't know you can check them with the command "ls -l".

**Comment by graingerkid** [comment]
I updated the path in models.py to the absolute location and it's working :)

Are you looking for contributors to this?

**Comment by crisbal** [comment]
Nice!

Yeah, if someone is willing to contribute I would be very happy! There is a _TODO_ list but the best thing to do right now is to check if everything is working and nothing is broken.

Right now I am a bit busy with school exams but in a few weeks I will have more free time to work on this and on other projects.

Can I ask you how did you find this project?

**Comment by graingerkid** [comment]
Just did a search in github for flask blog blueprint. I don't think the edit or delete buttons are working but if I can figure out peewee I can sort them for you - unless you get round to it first - I tend to stick to the mysqldb lib

**Comment by crisbal** [comment]
Be sure to have Javascript enabled and that the Javascript is beign loaded, at least for the delete. 

Edit should be just a link and the edit page need JS too. 

I used peewee because I didn't know much about SQL and peewee is pretty easy to learn and use for basic stuff.
